name: TestScan

on:
  workflow_dispatch

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install Qualys
        run: sudo docker run -d --restart on-failure -v /var/run/docker.sock:/var/run/docker.sock:ro -v /etc/qualys:/usr/local/qualys/qpa/data/conf/agent-data -v /usr/local/qualys/sensor/data:/usr/local/qualys/qpa/data -e ACTIVATIONID=ce990c19-eedb-4fbf-a93e-8437b4ac4545 -e CUSTOMERID=2bb876d1-105e-daa8-82c7-192aa63032e6 -e POD_URL=https://cmsqagpublic.qg1.apps.qualys.in/ContainerSensor --net=host --name qualys-container-sensor qualys/qcs-sensor:latest --cicd-deployed-sensor
        

      
          


